name: Test Secrets

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  get-secrets:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Print Secrets
        id: print_secrets
        run: |
          echo "${{ secrets.TEST_SECRET }}"
