name: Test Secrets

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  get-secrets:
    name: Get Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/Checkout@v4
        
      - name: Set Secrets with Action
        id: set_secrets
        uses: ./
        with:
          milliseconds: 1000

      - name: Print Secrets
        id: print_secrets
        run: |
          echo "TEST_SECRET = ${{ secrets.TEST_SECRET }}"
